researched logging service
avisi-apps/gaps pull request #16
Opened 2022-10-25 10:58 UTC by R-Gerrits

Closes: #15

2022-10-25 11:11 UTC, mitchelkuijpers requested changes

2022-10-25 11:11 UTC, mitchelkuijpers commented on modules/log/src/com/avisi_apps/gaps/docs/adr-001-clientside-logging-services.md
> +For this we are looking at their feature set, alongside it would be nice to have sometype of analitics available.
analitics -> analytics

2022-10-25 11:11 UTC, mitchelkuijpers commented on modules/log/src/com/avisi_apps/gaps/docs/adr-001-clientside-logging-services.md
> +- Build in support to include browserinformation with the log messages.
Build in -> Built-in

2022-10-25 11:11 UTC, mitchelkuijpers commented on modules/log/src/com/avisi_apps/gaps/docs/adr-001-clientside-logging-services.md
> +For our implementation of a logging service in our apps.
Ik zou dit eerder client-side error tracking noemen

2022-10-25 11:11 UTC, mitchelkuijpers commented on modules/log/src/com/avisi_apps/gaps/docs/adr-001-clientside-logging-services.md
> +- Rollbar had good integration with the other tools witch we use such as: Slack, github, Jira and PagerDuty, for these intergrations there are docs provided by Rolbar on how to set them up.
had -> has

2022-10-25 11:11 UTC, mitchelkuijpers commented on modules/log/src/com/avisi_apps/gaps/docs/adr-001-clientside-logging-services.md
> +- Rollbar had good integration with the other tools witch we use such as: Slack, github, Jira and PagerDuty, for these intergrations there are docs provided by Rolbar on how to set them up.
intergrations -> integrations

2022-10-25 11:11 UTC, mitchelkuijpers commented on modules/log/src/com/avisi_apps/gaps/docs/adr-001-clientside-logging-services.md
> +- Further is there good documentation available over their API, functionality and is there support for sourcemaps build in.
Further is -> There is
over their API -> about the API

2022-10-25 11:11 UTC, mitchelkuijpers commented on modules/log/src/com/avisi_apps/gaps/docs/adr-001-clientside-logging-services.md
> +LogRocket is not a suitable service for our needs and does not meet our requirements. This is why LogRocket was not chosen as the solution.
Deze zin kan weg omdat het al onder not chosen solutions valt

2022-10-25 11:11 UTC, mitchelkuijpers commented on modules/log/src/com/avisi_apps/gaps/docs/adr-001-clientside-logging-services.md
> +- It does not supports sourcemaps.
supports -> support

2022-11-29 12:39 UTC, mitchelkuijpers requested changes

2022-11-29 12:39 UTC, mitchelkuijpers commented on modules/log/src/com/avisi_apps/gaps/rollbar/api.cljs
> +             :freeSocketTimeout 30000}))
Dit is hele vreemde formatting

2022-11-29 12:39 UTC, mitchelkuijpers commented on modules/log/src/com/avisi_apps/gaps/rollbar/api.cljs
> +(declare token)
waarom staat dit hier?

2022-11-29 12:39 UTC, mitchelkuijpers commented on modules/log/src/com/avisi_apps/gaps/rollbar/api.cljs
> +(def token "ff24d39dcc4b46478685f282d8c1ce15")
Hoe kan ik nu de token configureren voor projecten?

2022-11-29 12:51 UTC, R-Gerrits commented on modules/log/src/com/avisi_apps/gaps/rollbar/api.cljs
> +(declare token)
Die declare is inderdaad onnodig ik dacht dat ik die nodig had om de token echt te zetten.

2022-11-29 13:13 UTC, R-Gerrits commented on modules/log/src/com/avisi_apps/gaps/rollbar/api.cljs
> +(def token "ff24d39dcc4b46478685f282d8c1ce15")
Ik was van plan om dit in een ander PR te doen omdat ik het zie als een andere feature. 
Dit komt doordat de keuze om het bijvoorbeeld op de "modules/functions/.logAPIToken" locatie te doen. Onderzocht/onderbouwd moet worden en dan ook geïmplementeerd. Hierdoor zie ik het als een aparte PR naar de epic toe.

Ik was van plan om het probleem op te delen in 3 PR's naar de epic
1. Hoe verbind ik met de te kiezen service? (Deze PR)
2. Waar laat ik doe toegangstoken (die jouw vraag beantwoord)
3. Hoe gaat de app deze functie aanroepen wanneer nodig (Bijv. boolean in de Fulcro state)

Maar nu ik er meer over nadenk is er ook wel wat voor te zeggen om dit als 1 feature te zien. Hoe zou jij dit aanpakken/ willen zien?

2022-11-29 13:18 UTC, R-Gerrits commented on modules/log/src/com/avisi_apps/gaps/rollbar/api.cljs
> +             :freeSocketTimeout 30000}))
Ik heb dit aangepast zodat de spacing overeen komt met atlas-crm-connect

2022-11-29 13:31 UTC, mitchelkuijpers commented on modules/log/src/com/avisi_apps/gaps/rollbar/api.cljs
> +(def token "ff24d39dcc4b46478685f282d8c1ce15")
Van mij mag je het als losse PR doen, duidelijk.

2022-12-06 07:50 UTC, merged